### ISSUE TITLE
More information around environment variables

### ISSUE THREAD

**Issue by dabit3** [Anish-Agnihotri/GateRepo#2]
I'm looking to get this up and running but unsure about these three environment variables:

```
NEXTAUTH_URL=""
NEXTAUTH_SECRET=""
DATABASE_URL=""
```

I'm guessing that `NEXTAUTH_URL` and `NEXTAUTH_SECRET` are referring to the configuration for [`next-auth`](https://next-auth.js.org/configuration/options)? What about the `DATABASE_URL`?

The others make sense already. It would be helpful to get these documented or commented somewhere to provide enough context to get started building with this.

Thanks!!

**Comment by Anish-Agnihotri** [comment]
Good call! Added in some documentation on the variables [here](https://github.com/Anish-Agnihotri/GateRepo#environment-variables).

LMK if this is along the lines of what you were looking for.

**Comment by dabit3** [comment]
Yo, this is PERFECT! Thank you!!
